version: "3"
services:
 client:
  image: "dsinkey9/multi-client"
  mem_limit: 128m
  hostname: client
 server:
  image: "dsinkey9/multi-server"
  mem_limit: 128m
  hostname: api
  environment:
    - REDIS_HOST=$REDIS_HOST
    - REDIS_PORT=$REDIS_PORT
    - PGUSER=$PGUSER
    - PGHOST=$PGHOST
    - PGDATABASE=$PGDATABASE
    - PGPASSWORD=$PGPASSWORD
    - PGPORT=$PGPORT
 worker:
  image: "dsinkey9/multi-worker"
  mem_limit: 128m
  hostname: worker
  environment:
    - REDIS_HOST=$REDIS_HOST
    - REDIS_PORT=$REDIS_PORT
 nginx:
  image: "dsinkey9/multi-nginx"
  mem_limit: 128m
  hostname: nginx
  ports:
    - "80:80"
